package com.safemode.llconnect.ui.theme

import androidx.compose.ui.graphics.Color

// Brand palette — a deep automotive blue/teal with amber accents.
val md_primary_light = Color(0xFF00629D)
val md_onPrimary_light = Color(0xFFFFFFFF)
val md_primaryContainer_light = Color(0xFFCFE5FF)
val md_onPrimaryContainer_light = Color(0xFF001D34)
val md_secondary_light = Color(0xFF51606F)
val md_onSecondary_light = Color(0xFFFFFFFF)
val md_secondaryContainer_light = Color(0xFFD4E4F6)
val md_onSecondaryContainer_light = Color(0xFF0D1D2A)
val md_tertiary_light = Color(0xFF8B5000)
val md_onTertiary_light = Color(0xFFFFFFFF)
val md_tertiaryContainer_light = Color(0xFFFFDCBE)
val md_onTertiaryContainer_light = Color(0xFF2C1600)
val md_error_light = Color(0xFFBA1A1A)
val md_onError_light = Color(0xFFFFFFFF)
val md_background_light = Color(0xFFFCFCFF)
val md_onBackground_light = Color(0xFF1A1C1E)
val md_surface_light = Color(0xFFFCFCFF)
val md_onSurface_light = Color(0xFF1A1C1E)
val md_surfaceVariant_light = Color(0xFFDDE3EA)
val md_onSurfaceVariant_light = Color(0xFF41474D)
val md_outline_light = Color(0xFF71787E)

val md_primary_dark = Color(0xFF99CBFF)
val md_onPrimary_dark = Color(0xFF003355)
val md_primaryContainer_dark = Color(0xFF004A78)
val md_onPrimaryContainer_dark = Color(0xFFCFE5FF)
val md_secondary_dark = Color(0xFFB8C8DA)
val md_onSecondary_dark = Color(0xFF233240)
val md_secondaryContainer_dark = Color(0xFF394857)
val md_onSecondaryContainer_dark = Color(0xFFD4E4F6)
val md_tertiary_dark = Color(0xFFFFB870)
val md_onTertiary_dark = Color(0xFF4A2800)
val md_tertiaryContainer_dark = Color(0xFF693C00)
val md_onTertiaryContainer_dark = Color(0xFFFFDCBE)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_background_dark = Color(0xFF1A1C1E)
val md_onBackground_dark = Color(0xFFE2E2E5)
val md_surface_dark = Color(0xFF1A1C1E)
val md_onSurface_dark = Color(0xFFE2E2E5)
val md_surfaceVariant_dark = Color(0xFF41474D)
val md_onSurfaceVariant_dark = Color(0xFFC1C7CE)
val md_outline_dark = Color(0xFF8B9198)
